### ISSUE TITLE
periodically writes to the console and then crashes

### ISSUE THREAD

**Issue by Gorbanev9999** [NockyCZ/CS2-Discord-Utilities#17]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.UInt64.Parse(String s)
   at DiscordUtilities.DiscordUtilities.PerformChatlog(UInt64 playerSteamID, String message, Int32 team, Boolean isTeamMessage) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\DiscordUtilities\Sections\Chatlog.cs:line 18
   at DiscordUtilities.DiscordUtilities.OnPlayerSayTeam(CCSPlayerController player, CommandInfo info) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\DiscordUtilities\Events.cs:line 94
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass48_0.<AddCommandListener>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 216
   at InvokeStub_Func`3.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Gorbanev9999** [comment]
sharp 213

**Comment by NockyCZ** [comment]
Invalid channel id

**Comment by Gorbanev9999** [comment]
> Неверный идентификатор канала

в какой ветке? т.к функции работают где указаны индификаторы, индификатор может повторятся?
