### ISSUE TITLE
Server status bug

### ISSUE THREAD

**Issue by tungsten35** [NockyCZ/CS2-Discord-Utilities#22]
When I enable URL button thing I get error(ServerStatus):

 ---> System.InvalidOperationException: The url steam://connect/185.171.25.17:27015 must include a protocol (either HTTP, HTTPS, or DISCORD)
   at Discord.Utils.UrlValidation.ValidateButton(String url)
   at Discord.ButtonBuilder.Build()
   at Discord.ComponentBuilder.WithButton(ButtonBuilder button, Int32 row)
   at DiscordUtilities.DiscordUtilities.GetComponentsBuilder(Builder componentBuilder) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\DiscordUtilities\Functions\Helpers.cs:line 145
   at DiscordUtilities.DiscordUtilities.SendCustomMessageToChannel(String customId, UInt64 channelId, String content, Builder embed, Builder components, Boolean saveMessage) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\DiscordUtilities\API\Actions.cs:line 158
   at ServerStatus.ServerStatus.SetupServerStatus() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\Addons\DU_ServerStatus\ServerStatus.cs:line 149
   at ServerStatus.ServerStatus.OnBotLoaded() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\Addons\DU_ServerStatus\ServerStatus.cs:line 36
   at ServerStatus.ServerStatus.DiscordUtilitiesEventHandler(Object _, IDiscordUtilitiesEvent event) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\Addons\DU_ServerStatus\ServerStatus.cs:line 80
   at DiscordUtilities.DiscordUtilities.TriggerEvent(IDiscordUtilitiesEvent event) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\DiscordUtilities\API\Events.cs:line 16
   at DiscordUtilities.DiscordUtilities.<>c.<BotLoaded>b__25_0() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Discord Utilities\DiscordUtilities\API\Events.cs:line 57
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

**Comment by NockyCZ** [comment]
```---> System.InvalidOperationException: The url steam://connect/185.171.25.17:27015 must include a protocol (either HTTP, HTTPS, or DISCORD)```

Invalid Button URL, you need to use https://example.com
