### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by Truyn** [NockyCZ/CS2-Discord-Utilities#36]
After updating to 2.0.8, !report stopped coming.
 The configuration is identical.
 
  [#43:LOADED]: "[Discord Utilities] Report System" (1.2) by SourceFactory.eu
    [#15:LOADED]: "Discord Utilities" (2.0.8) by Nocky (SourceFactory.eu)

**Comment by Truyn** [comment]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.UInt64.Parse(String s)
   at Report.Report.SendReport(CCSPlayerController sender, CCSPlayerController target, String reason) in C:\Users\Mates-PC\Desktop\SourceFactory\Github\CS2-Discord-Utilities\src\Modules\Report\Report.cs:line 210
   at Report.Report.<>c__DisplayClass7_1.<OpenReportMenu_Reason>b__1(CCSPlayerController player, ChatMenuOption target) in C:\Users\Mates-PC\Desktop\SourceFactory\Github\CS2-Discord-Utilities\src\Modules\Report\Menus.cs:line 95
   at CounterStrikeSharp.API.Modules.Menu.BaseMenuInstance.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs:line 130
   at CounterStrikeSharp.API.Core.Application.<>c.<Start>b__16_0(CCSPlayerController player, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 101
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by NockyCZ** [comment]
Channel id is empty

**Comment by Truyn** [comment]
thx
